///=========== Auth Section Label Keys =====================================
const String welcomeToZamapay = 'welcomeToZamapay';
const String simplifyTransactions = 'simplifyTransactions';
const String depositFunds = 'depositFunds';
const String enableAgents = 'enableAgents';
const String withdrawFunds = 'withdrawFunds';
const String allowAgents = 'allowAgents';
const String welcomeBack = 'welcomeBack';
const String signIn = 'signIn';
const String enterPhoneNumber = 'enterPhoneNumber';
const String phoneAlt = 'phoneAlt';
const String phoneNumber = 'phoneNumber';
const String enterPassword = 'enterPassword';
const String lock = 'lock';
const String password = 'password';
const String forgotPassword = 'forgotPassword';
const String login = 'login';
const String noAccountSignUp = 'noAccountSignUp';
const String signUpAsAgent = 'signUpAsAgent';
const String signUpAsShop = 'signUpAsShop';
const String signUp = 'signUp';
const String simpleStepsAgent = 'simpleStepsAgent';
const String uploadPhoto = 'uploadPhoto';
const String firstName = 'firstName';
const String lastName = 'lastName';
const String email = 'email';
const String location = 'location';
const String gender = 'gender';
const String next = 'next';
const String registration = 'registration';
const String createAccount = 'createAccount';
const String fullName = 'fullName';
const String shopName = 'shopName';
const String businessType = 'businessType';
const String typeOfBusiness = 'typeOfBusiness';
const String centerFace = 'centerFace';
const String pointFaceRight = 'pointFaceRight';
const String verificationCode = 'verificationCode';
const String resendCode = 'resendCode';
const String continueKey = 'continue';
const String forgotPasswordTitle = 'forgotPasswordTitle';
const String enterPhoneNumberToReset = 'enterPhoneNumberToReset';
const String sendOTP = 'sendOTP';
const String newPassword = 'newPassword';
const String createSafePassword = 'createSafePassword';
const String confirmPassword = 'confirmPassword';
const String passwordChanged = 'passwordChanged';
const String passwordChangedSuccess = 'passwordChangedSuccess';
const String welcome = 'welcome';
const String accountValidated = 'accountValidated';
const String activateAccount = 'activateAccount';
const String completeActivation = 'completeActivation';
const String readAndAcceptLegal = 'readAndAcceptLegal';
const String acceptConditions = 'acceptConditions';
const String uploadDocument = 'uploadDocument';
const String submit = 'submit';
const String accountActive = 'accountActive';
const String accountActiveMessage = 'accountActiveMessage';
const String finish = 'finish';

/// ================ Auth Section Completed Here ============================

/// ================ Profile Screen =========================================
const String myAccount = "myAccount";
const String changePassword = "changePassword";
const String notification = "notification";
const String themes = "themes";
const String languages = "languages";
const String helpCenter = "helpCenter";
const String contactSupport = "contactSupport";
const String fontSize = "fontSize";
const String logout = "logout";
const String changePicture = 'changePicture';
const String saveChanges = 'saveChanges';

///================ Change Password Keys ===================================
const String changePasswordKey = "change_password";
const String enterCurrentAndNewPasswordsKey = "enter_current_and_new_passwords";
const String oldPasswordKey = "old_password";
const String passwordKey = "password";
const String newPasswordKey = "new_password";
const String confirmPasswordKey = "confirm_password";
const String confirmNewPasswordKey = "confirm_new_password";

/// ================ Notification Screen Keys ==============================
const String notificationKey = "notification";
const String systemAlertsKey = "system_alerts";
const String accountAlertsKey = "account_alerts";
const String systemUpdateKey = "system_update";
const String newKey = "new";

///================= Themes Keys =============================
const String themesKey = "themes";
const String lightModeKey = "light_mode";
const String darkModeKey = "dark_mode";

/// ================ Languages Keys ==========================
const String languageKey = "language";
const String englishKey = "english";
const String southAfricaKey = "south_africa";
const String spainKey = "spain";
const String franceKey = "france";

/// =============== Dashboard Keys ===========================
const String welcomeKey = "welcome";
const String depositFundsKey = "deposit_funds";
const String withdrawFundsKey = "withdraw_funds";
const String transferFundsKey = "transfer_funds";
const String transferReconciliationKey = "transfer_reconciliation";
const String utilityBillsKey = "utility_bills";
const String nameKey = "name";
const String currentBalanceKey = "current_balance";
const String operationAccountKey = "operation_account";
const String transactionsKey = "transactions";
const String seeAllKey = "see_all";
const String withdrawKey = "withdraw";
const String transferKey = "transfer";
const String depositKey = "deposit";
const String transferToPartnerKey = "transfer_to_partner";
const String bankTransactionsKey = "bank_transactions";
const String topUpKey = "top_up";
const String reconciliationsKey = "reconciliations";
const String totalBalanceKey = "total_balance";

/// ================= Confirmation Keys ===========================
const String confirmKey = "confirm";
const String depositSummaryKey = "deposit_summary";
const String transactionNumberKey = "transaction_number";
const String countryOfReceptionKey = "country_of_reception";
const String paymentTypeKey = "payment_type";
const String dateTimeKey = "date_time";
const String subTotalKey = "sub_total";
const String feeKey = "fee";
const String totalPaymentKey = "total_payment";

/// ================= Transaction Succes Screen ====================
const String depositSuccessKey = "deposit_success";
const String securelyPaidViaKey = "securely_paid_via";
const String fromKey = "from";
const String toKey = "to";
const String totalDepositKey = "total_deposit";
const String backToHomeKey = "back_to_home";
const String myQrKey = "my_qr";
const String greatKey = "great";
const String homeKey = "home";
const String analyticsKey = "analytics";
const String erpKey = "erp";
const String groupsKey = "groups";
const String historyKey = "history";
const String totalAssetValueKey = "total_asset_value";
const String monthKey = "month";
const String weekKey = "week";
const String customerNameKey = "customer_name";
const String selectBankKey = "select_bank";
const String accountNumberKey = "account_number";
const String amountKey = "amount";
const String optionalKey = "optional";
const String profileKey = "profile";
